version: '3.9'

services:
  linker-link-api:
    image: linker-link-api-img
    build:
      context: ./backend/link/src
      dockerfile: Dockerfile
    container_name: linker-link-api
    ports:
      - "8080:8080"
    depends_on:
      - linker-link-db
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=db;Port=5432;Database=db_linker_link;Username=admin;Password=admin123
    networks:
      - app-net

  linker-frontend:
    image: linker-frontend-img
    build:
      context: ./frontend
    container_name: linker-frontend
    ports:
      - "3000:80"
    depends_on:
      - linker-link-api
    networks:
      - app-net

  linker-link-db:
    image: postgres:16-alpine
    container_name: linker-db
    environment:
      POSTGRES_DB: db_linker_link
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  postgres_data:
